namespace: noterius
containers:
  db:
    image: orchardup/postgresql:latest
    env:
      POSTGRESQL_DB: noterius
      POSTGRESQL_USER: nota
      POSTGRESQL_PASS: notadefault
    volumes_from:
      - db_storage
    ports:
      - "5432:5432"

  db_storage:
    image: grammarly/scratch:latest
    state: created
    volumes:
      - /var/log/postgresql
      - /var/lib/postgresql

  emulator:
    image: nyarum/noterius:latest
    entrypoint: ["reflex", "-r", '\.go$', "-s","--", "go", "run", "main.go", "-dbip", "{{ bridgeIp }}"]
    volumes:
      - .:/go/src/github.com/Nyarum/noterius
    add_host:
      - db:{{ bridgeIp }}
    ports:
      - "1973:1973"